# Generated by Django 4.2.16 on 2024-09-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('upvote', models.IntegerField(default=0)),
                ('financial_projection', models.TextField()),
                ('icon', models.ImageField(upload_to='images/')),
                ('screenshot', models.ImageField(upload_to='images/screenshots/')),
                ('link', models.URLField()),
                ('pub_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('developer', models.ForeignKey(limit_choices_to={'is_developer': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(limit_choices_to={'is_investor': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
