# Generated by Django 4.2.16 on 2025-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_investment_equity_alter_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='funding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
